-- Runtime Oracle schema for application chat/LLM features.
-- This file creates the tables referenced by:
--   - app/server/core/chat_app/prompts/sql_agent.py
--   - app/server/core/dynamic_app/prompts/sql_agent.py
--   - app/server/chat_app/rag_tool.py
--   - app/server/database/connections.py
--
-- Includes:
--   1) Power-grid relational schema used by NL2SQL generation/execution
--   2) EDGE_DEMO_EMBEDDING vector table used for RAG semantic search

CREATE TABLE SUBSTATIONS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(150) NOT NULL,
    code VARCHAR2(40) NOT NULL,
    latitude NUMBER(10,6),
    longitude NUMBER(10,6),
    capacity_mva NUMBER(10,2),
    status VARCHAR2(30),
    CONSTRAINT uq_substations_code UNIQUE (code)
);

CREATE TABLE CIRCUITS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    circuit_name VARCHAR2(150) NOT NULL,
    circuit_code VARCHAR2(40) NOT NULL,
    substation_id NUMBER NOT NULL,
    voltage_kv NUMBER(8,2),
    customers_served NUMBER,
    avg_load_mw NUMBER(10,2),
    peak_load_mw NUMBER(10,2),
    neighborhood VARCHAR2(120),
    CONSTRAINT uq_circuits_code UNIQUE (circuit_code),
    CONSTRAINT fk_circuits_substation FOREIGN KEY (substation_id) REFERENCES SUBSTATIONS (id)
);

CREATE TABLE ASSETS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id VARCHAR2(50) NOT NULL,
    asset_type VARCHAR2(60) NOT NULL,
    circuit_id NUMBER,
    substation_id NUMBER,
    condition_score NUMBER(5,2),
    health_index NUMBER(5,2),
    status VARCHAR2(30),
    criticality VARCHAR2(30),
    CONSTRAINT uq_assets_asset_id UNIQUE (asset_id),
    CONSTRAINT fk_assets_circuit FOREIGN KEY (circuit_id) REFERENCES CIRCUITS (id),
    CONSTRAINT fk_assets_substation FOREIGN KEY (substation_id) REFERENCES SUBSTATIONS (id)
);

CREATE TABLE CUSTOMERS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR2(50) NOT NULL,
    name VARCHAR2(200) NOT NULL,
    customer_type VARCHAR2(40),
    circuit_id NUMBER,
    avg_monthly_usage_kwh NUMBER(12,2),
    peak_demand_kw NUMBER(12,2),
    sla_priority VARCHAR2(30),
    CONSTRAINT uq_customers_account_number UNIQUE (account_number),
    CONSTRAINT fk_customers_circuit FOREIGN KEY (circuit_id) REFERENCES CIRCUITS (id)
);

CREATE TABLE OUTAGES (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_code VARCHAR2(50) NOT NULL,
    circuit_id NUMBER NOT NULL,
    root_cause_asset_id NUMBER,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    cause_category VARCHAR2(60),
    customers_affected NUMBER,
    duration_minutes NUMBER,
    CONSTRAINT uq_outages_incident_code UNIQUE (incident_code),
    CONSTRAINT fk_outages_circuit FOREIGN KEY (circuit_id) REFERENCES CIRCUITS (id),
    CONSTRAINT fk_outages_root_asset FOREIGN KEY (root_cause_asset_id) REFERENCES ASSETS (id)
);

CREATE TABLE WORK_ORDERS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outage_id NUMBER,
    asset_id NUMBER,
    work_type VARCHAR2(60),
    priority VARCHAR2(30),
    status VARCHAR2(30),
    labor_hours NUMBER(10,2),
    material_cost NUMBER(12,2),
    CONSTRAINT fk_work_orders_outage FOREIGN KEY (outage_id) REFERENCES OUTAGES (id),
    CONSTRAINT fk_work_orders_asset FOREIGN KEY (asset_id) REFERENCES ASSETS (id)
);

CREATE TABLE DOCUMENTS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type VARCHAR2(50),
    title VARCHAR2(250) NOT NULL,
    related_outage_id NUMBER,
    related_asset_id NUMBER,
    related_circuit_id NUMBER,
    tags VARCHAR2(500),
    author VARCHAR2(120),
    document_date DATE,
    CONSTRAINT fk_documents_outage FOREIGN KEY (related_outage_id) REFERENCES OUTAGES (id),
    CONSTRAINT fk_documents_asset FOREIGN KEY (related_asset_id) REFERENCES ASSETS (id),
    CONSTRAINT fk_documents_circuit FOREIGN KEY (related_circuit_id) REFERENCES CIRCUITS (id)
);

CREATE TABLE CREW_ASSIGNMENTS (
    crew_id NUMBER NOT NULL,
    outage_id NUMBER NOT NULL,
    dispatch_time TIMESTAMP,
    arrival_time TIMESTAMP,
    CONSTRAINT pk_crew_assignments PRIMARY KEY (crew_id, outage_id),
    CONSTRAINT fk_crew_assignments_outage FOREIGN KEY (outage_id) REFERENCES OUTAGES (id)
);

CREATE TABLE CUSTOMER_COMPLAINTS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    outage_id NUMBER,
    category VARCHAR2(60),
    status VARCHAR2(30),
    complaint_time TIMESTAMP,
    resolution VARCHAR2(1000),
    CONSTRAINT fk_customer_complaints_customer FOREIGN KEY (customer_id) REFERENCES CUSTOMERS (id),
    CONSTRAINT fk_customer_complaints_outage FOREIGN KEY (outage_id) REFERENCES OUTAGES (id)
);

CREATE TABLE ASSET_HEALTH_HISTORY (
    asset_id NUMBER NOT NULL,
    reading_time TIMESTAMP NOT NULL,
    condition_score NUMBER(5,2),
    temperature_c NUMBER(8,2),
    load_pct NUMBER(5,2),
    CONSTRAINT pk_asset_health_history PRIMARY KEY (asset_id, reading_time),
    CONSTRAINT fk_asset_health_history_asset FOREIGN KEY (asset_id) REFERENCES ASSETS (id)
);

CREATE TABLE EDGE_DEMO_EMBEDDING (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR2(4000),
    vec VECTOR,
    source VARCHAR2(100)
);
