-- Demo Oracle schema for Terrena LLM/chat and agent sample questions.
-- Designed to support sample questions around alerts, filieres, brands,
-- logistics, quality, traceability, lots, campaigns, sites, and action plans.

CREATE TABLE territories (
    territory_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    territory_name VARCHAR2(100) NOT NULL,
    territory_code VARCHAR2(30) NOT NULL,
    region_name VARCHAR2(100),
    risk_level VARCHAR2(20) CHECK (risk_level IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    logistics_pressure_score NUMBER(5,2),
    notes VARCHAR2(500),
    CONSTRAINT uq_territories_code UNIQUE (territory_code)
);

CREATE TABLE filieres (
    filiere_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filiere_name VARCHAR2(100) NOT NULL,
    filiere_code VARCHAR2(30) NOT NULL,
    category VARCHAR2(60),
    strategic_priority VARCHAR2(20) CHECK (strategic_priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    active_flag CHAR(1) DEFAULT 'Y' NOT NULL CHECK (active_flag IN ('Y', 'N')),
    CONSTRAINT uq_filieres_code UNIQUE (filiere_code)
);

CREATE TABLE brands (
    brand_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_name VARCHAR2(120) NOT NULL,
    brand_code VARCHAR2(40) NOT NULL,
    business_line VARCHAR2(100),
    export_flag CHAR(1) DEFAULT 'N' NOT NULL CHECK (export_flag IN ('Y', 'N')),
    quality_sensitivity VARCHAR2(20) CHECK (quality_sensitivity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    CONSTRAINT uq_brands_code UNIQUE (brand_code)
);

CREATE TABLE campaigns (
    campaign_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_name VARCHAR2(120) NOT NULL,
    campaign_year NUMBER(4) NOT NULL,
    season_name VARCHAR2(40),
    start_date DATE,
    end_date DATE,
    status VARCHAR2(20) CHECK (status IN ('PLANNED', 'ACTIVE', 'CLOSING', 'CLOSED'))
);

CREATE TABLE sites (
    site_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_name VARCHAR2(150) NOT NULL,
    site_code VARCHAR2(40) NOT NULL,
    site_type VARCHAR2(40) NOT NULL,
    territory_id NUMBER NOT NULL,
    filiere_id NUMBER,
    city_name VARCHAR2(100),
    capacity_tons NUMBER(10,2),
    status VARCHAR2(20) CHECK (status IN ('ACTIVE', 'WATCH', 'DISRUPTED', 'MAINTENANCE')),
    CONSTRAINT uq_sites_code UNIQUE (site_code),
    CONSTRAINT fk_sites_territory FOREIGN KEY (territory_id) REFERENCES territories (territory_id),
    CONSTRAINT fk_sites_filiere FOREIGN KEY (filiere_id) REFERENCES filieres (filiere_id)
);

CREATE TABLE brand_filieres (
    brand_id NUMBER NOT NULL,
    filiere_id NUMBER NOT NULL,
    importance_level VARCHAR2(20) CHECK (importance_level IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    PRIMARY KEY (brand_id, filiere_id),
    CONSTRAINT fk_brand_filieres_brand FOREIGN KEY (brand_id) REFERENCES brands (brand_id),
    CONSTRAINT fk_brand_filieres_filiere FOREIGN KEY (filiere_id) REFERENCES filieres (filiere_id)
);

CREATE TABLE brand_sites (
    brand_id NUMBER NOT NULL,
    site_id NUMBER NOT NULL,
    role_name VARCHAR2(60),
    PRIMARY KEY (brand_id, site_id),
    CONSTRAINT fk_brand_sites_brand FOREIGN KEY (brand_id) REFERENCES brands (brand_id),
    CONSTRAINT fk_brand_sites_site FOREIGN KEY (site_id) REFERENCES sites (site_id)
);

CREATE TABLE operational_alerts (
    alert_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_code VARCHAR2(40) NOT NULL,
    alert_title VARCHAR2(200) NOT NULL,
    alert_type VARCHAR2(40) NOT NULL,
    severity VARCHAR2(20) NOT NULL CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    status VARCHAR2(30) NOT NULL CHECK (status IN ('OPEN', 'IN_ANALYSIS', 'MITIGATING', 'RESOLVED', 'MONITORING')),
    filiere_id NUMBER,
    territory_id NUMBER,
    site_id NUMBER,
    campaign_id NUMBER,
    opened_at DATE NOT NULL,
    expected_resolution_at DATE,
    impact_summary VARCHAR2(500),
    impact_units NUMBER(12,2),
    impact_unit_label VARCHAR2(60),
    cause_summary VARCHAR2(500),
    assigned_team VARCHAR2(150),
    escalation_required CHAR(1) DEFAULT 'N' NOT NULL CHECK (escalation_required IN ('Y', 'N')),
    CONSTRAINT uq_operational_alerts_code UNIQUE (alert_code),
    CONSTRAINT fk_operational_alerts_filiere FOREIGN KEY (filiere_id) REFERENCES filieres (filiere_id),
    CONSTRAINT fk_operational_alerts_territory FOREIGN KEY (territory_id) REFERENCES territories (territory_id),
    CONSTRAINT fk_operational_alerts_site FOREIGN KEY (site_id) REFERENCES sites (site_id),
    CONSTRAINT fk_operational_alerts_campaign FOREIGN KEY (campaign_id) REFERENCES campaigns (campaign_id)
);

CREATE TABLE alert_brand_impacts (
    alert_id NUMBER NOT NULL,
    brand_id NUMBER NOT NULL,
    impact_level VARCHAR2(20) NOT NULL CHECK (impact_level IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    impact_description VARCHAR2(400),
    PRIMARY KEY (alert_id, brand_id),
    CONSTRAINT fk_alert_brand_impacts_alert FOREIGN KEY (alert_id) REFERENCES operational_alerts (alert_id),
    CONSTRAINT fk_alert_brand_impacts_brand FOREIGN KEY (brand_id) REFERENCES brands (brand_id)
);

CREATE TABLE logistics_flows (
    flow_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flow_code VARCHAR2(40) NOT NULL,
    flow_name VARCHAR2(160) NOT NULL,
    filiere_id NUMBER NOT NULL,
    brand_id NUMBER,
    origin_site_id NUMBER NOT NULL,
    destination_site_id NUMBER NOT NULL,
    campaign_id NUMBER,
    transport_mode VARCHAR2(40),
    service_level_pct NUMBER(5,2),
    on_time_delivery_pct NUMBER(5,2),
    backlog_tons NUMBER(10,2),
    weekly_volume_tons NUMBER(10,2),
    weather_risk_level VARCHAR2(20) CHECK (weather_risk_level IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    flow_status VARCHAR2(20) CHECK (flow_status IN ('NORMAL', 'WATCH', 'DEGRADED', 'BLOCKED')),
    notes VARCHAR2(500),
    CONSTRAINT uq_logistics_flows_code UNIQUE (flow_code),
    CONSTRAINT fk_logistics_flows_filiere FOREIGN KEY (filiere_id) REFERENCES filieres (filiere_id),
    CONSTRAINT fk_logistics_flows_brand FOREIGN KEY (brand_id) REFERENCES brands (brand_id),
    CONSTRAINT fk_logistics_flows_origin FOREIGN KEY (origin_site_id) REFERENCES sites (site_id),
    CONSTRAINT fk_logistics_flows_destination FOREIGN KEY (destination_site_id) REFERENCES sites (site_id),
    CONSTRAINT fk_logistics_flows_campaign FOREIGN KEY (campaign_id) REFERENCES campaigns (campaign_id)
);

CREATE TABLE lots (
    lot_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lot_code VARCHAR2(50) NOT NULL,
    filiere_id NUMBER NOT NULL,
    brand_id NUMBER,
    source_site_id NUMBER NOT NULL,
    current_site_id NUMBER NOT NULL,
    campaign_id NUMBER,
    production_date DATE,
    expiration_date DATE,
    quantity NUMBER(12,2),
    quantity_unit VARCHAR2(30),
    traceability_status VARCHAR2(20) CHECK (traceability_status IN ('CLEAR', 'WATCH', 'AT_RISK', 'BLOCKED')),
    quality_status VARCHAR2(20) CHECK (quality_status IN ('CONFORMING', 'REVIEW', 'NON_CONFORMING', 'RELEASED')),
    destination_market VARCHAR2(60),
    export_flag CHAR(1) DEFAULT 'N' NOT NULL CHECK (export_flag IN ('Y', 'N')),
    CONSTRAINT uq_lots_code UNIQUE (lot_code),
    CONSTRAINT fk_lots_filiere FOREIGN KEY (filiere_id) REFERENCES filieres (filiere_id),
    CONSTRAINT fk_lots_brand FOREIGN KEY (brand_id) REFERENCES brands (brand_id),
    CONSTRAINT fk_lots_source_site FOREIGN KEY (source_site_id) REFERENCES sites (site_id),
    CONSTRAINT fk_lots_current_site FOREIGN KEY (current_site_id) REFERENCES sites (site_id),
    CONSTRAINT fk_lots_campaign FOREIGN KEY (campaign_id) REFERENCES campaigns (campaign_id)
);

CREATE TABLE quality_issues (
    quality_issue_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_code VARCHAR2(40) NOT NULL,
    lot_id NUMBER,
    site_id NUMBER,
    brand_id NUMBER,
    issue_category VARCHAR2(60) NOT NULL,
    severity VARCHAR2(20) NOT NULL CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    status VARCHAR2(30) NOT NULL CHECK (status IN ('OPEN', 'UNDER_REVIEW', 'ESCALATED', 'RESOLVED')),
    detected_at DATE NOT NULL,
    owner_name VARCHAR2(120),
    summary VARCHAR2(500),
    action_required VARCHAR2(500),
    CONSTRAINT uq_quality_issues_code UNIQUE (issue_code),
    CONSTRAINT fk_quality_issues_lot FOREIGN KEY (lot_id) REFERENCES lots (lot_id),
    CONSTRAINT fk_quality_issues_site FOREIGN KEY (site_id) REFERENCES sites (site_id),
    CONSTRAINT fk_quality_issues_brand FOREIGN KEY (brand_id) REFERENCES brands (brand_id)
);

CREATE TABLE traceability_checks (
    check_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lot_id NUMBER NOT NULL,
    site_id NUMBER NOT NULL,
    check_date DATE NOT NULL,
    check_status VARCHAR2(20) NOT NULL CHECK (check_status IN ('PASS', 'WARNING', 'FAIL')),
    indicator_name VARCHAR2(120) NOT NULL,
    indicator_value NUMBER(8,2),
    threshold_value NUMBER(8,2),
    unit_label VARCHAR2(30),
    finding_summary VARCHAR2(500),
    document_complete_flag CHAR(1) DEFAULT 'Y' NOT NULL CHECK (document_complete_flag IN ('Y', 'N')),
    CONSTRAINT fk_traceability_checks_lot FOREIGN KEY (lot_id) REFERENCES lots (lot_id),
    CONSTRAINT fk_traceability_checks_site FOREIGN KEY (site_id) REFERENCES sites (site_id)
);

CREATE TABLE reference_documents (
    document_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_code VARCHAR2(40) NOT NULL,
    document_title VARCHAR2(200) NOT NULL,
    document_type VARCHAR2(40) NOT NULL,
    related_filiere_id NUMBER,
    related_brand_id NUMBER,
    related_lot_id NUMBER,
    related_alert_id NUMBER,
    version_label VARCHAR2(30),
    owner_name VARCHAR2(120),
    document_status VARCHAR2(20) CHECK (document_status IN ('DRAFT', 'ACTIVE', 'ARCHIVED')),
    created_at DATE NOT NULL,
    CONSTRAINT uq_reference_documents_code UNIQUE (document_code),
    CONSTRAINT fk_reference_documents_filiere FOREIGN KEY (related_filiere_id) REFERENCES filieres (filiere_id),
    CONSTRAINT fk_reference_documents_brand FOREIGN KEY (related_brand_id) REFERENCES brands (brand_id),
    CONSTRAINT fk_reference_documents_lot FOREIGN KEY (related_lot_id) REFERENCES lots (lot_id),
    CONSTRAINT fk_reference_documents_alert FOREIGN KEY (related_alert_id) REFERENCES operational_alerts (alert_id)
);

CREATE TABLE action_plans (
    action_plan_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_code VARCHAR2(40) NOT NULL,
    alert_id NUMBER,
    brand_id NUMBER,
    site_id NUMBER,
    owner_name VARCHAR2(120) NOT NULL,
    priority VARCHAR2(20) NOT NULL CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    due_at DATE,
    status VARCHAR2(30) NOT NULL CHECK (status IN ('OPEN', 'IN_PROGRESS', 'BLOCKED', 'DONE')),
    action_summary VARCHAR2(500) NOT NULL,
    horizon_hours NUMBER(6),
    CONSTRAINT uq_action_plans_code UNIQUE (action_code),
    CONSTRAINT fk_action_plans_alert FOREIGN KEY (alert_id) REFERENCES operational_alerts (alert_id),
    CONSTRAINT fk_action_plans_brand FOREIGN KEY (brand_id) REFERENCES brands (brand_id),
    CONSTRAINT fk_action_plans_site FOREIGN KEY (site_id) REFERENCES sites (site_id)
);
